from django.urls import path
from django.views.generic.base import RedirectView
from .views import (
    dashboard_view,
    student_list_view,
    student_detail_view,
    student_registration_view,
    student_edit_view,
    enroll_student_view,
    bulk_grade_entry_view,
    class_report_card_view,
    compile_grades_view,
    register_staff_view,
    staff_list_view,
    staff_detail_view,
    staff_edit_view,
    login_view,
    logout_view,
    class_enrollment_portal_view,
    configure_session_view,
    global_search_view,
    api_class_subjects,
    api_class_details,
    api_subject_details,
    verify_class_rankings_view,
    view_account,
    midterm_summary_view,
    compile_midterm_grades_view,
    parents_list,
    parent_detail_view,
    parent_edit_view,
    assign_form_class,
    classes_subjects_hub,
    timetable_hub,
)

urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('dashboard/', dashboard_view, name='dashboard_alt'),
    path('e', RedirectView.as_view(url='/', permanent=False), name='e_redirect'),
    path('students/', student_list_view, name='student_list'),
    path('students/<int:student_id>/', student_detail_view, name='student_detail'),
    path('students/<int:student_id>/edit/', student_edit_view, name='student_edit'),
    path('students/register/', student_registration_view, name='student_registration'),
    path('students/register/', student_registration_view, name='register_student'),
    path('students/enroll/<int:student_id>/', enroll_student_view, name='enroll_student'),
    path('students/report/<int:class_id>/', class_report_card_view, name='class_report_card'),
    path('class/<int:class_id>/report/', class_report_card_view, name='class_report_card_short'),
    path('class/<int:class_id>/report/view/', class_report_card_view, name='class_report'),
    path('reports/', class_report_card_view, {'class_id': 1}, name='reports'),
    path('staff/register/', register_staff_view, name='register_staff'),
    path('staff/list/', staff_list_view, name='staff_list'),
    path('staff/<int:staff_id>/', staff_detail_view, name='staff_detail'),
    path('staff/<int:staff_id>/assign-form-class/', assign_form_class, name='assign_form_class'),
    path('staff/<int:staff_id>/edit/', staff_edit_view, name='staff_edit'),
    path('grades/entry/<int:class_id>/<int:subject_id>/', bulk_grade_entry_view, name='bulk_grade_entry'),
    path('reports/compile/', compile_grades_view, name='compile_grades'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('enrollment/portal/', class_enrollment_portal_view, name='class_enrollment_portal'),
    path('enrollment/portal/', class_enrollment_portal_view, name='promotion_portal'),
    path('settings/academic-session/', configure_session_view, name='configure_session'),
    path('settings/academic-session/', configure_session_view, name='academic_settings'),
    path('api/search/', global_search_view, name='global_search_api'),
    path('api/class-subjects/', api_class_subjects, name='api_class_subjects'),
    path('api/class-details/<int:class_id>/', api_class_details, name='api_class_details'),
    path('api/subject-details/<int:subject_id>/', api_subject_details, name='api_subject_details'),
    path('class/<int:class_id>/verify/', verify_class_rankings_view, name='verify_class_rankings'),
    path('master-summary/<int:class_id>/', class_report_card_view, name='master_continuous_assessment'),
    path('account/', view_account, name='view_account'),
    path('midterm/', midterm_summary_view, name='midterm_summary'),
    path('midterm/compile/', compile_midterm_grades_view, name='compile_midterm_grades'),
    path('parents/', parents_list, name='parents_list'),
    path('parents/<int:parent_id>/', parent_detail_view, name='parent_detail'),
    path('parents/<int:parent_id>/edit/', parent_edit_view, name='parent_edit'),
    path('classes-subjects/', classes_subjects_hub, name='classes_subjects_hub'),
    path('timetables/', timetable_hub, name='timetable_hub'),
]
