# Generated by Django 6.0.6 on 2026-06-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admisssion_number',
            new_name='admission_number',
        ),
    ]
