# Generated by Django 6.0.5 on 2026-06-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0002_rename_admisssion_number_student_admission_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('academic_year', models.CharField(max_length=9)),
                ('class_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.subject')),
            ],
        ),
    ]
