# Generated by Django 6.0.5 on 2026-06-26 12:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0003_subjectassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('residential_address', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='living_with',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Both', 'Both')], default='Both', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_attended',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Day', 'Day'), ('Boarder', 'Boarder')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_of', to='sis.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_of', to='sis.parent'),
        ),
    ]
