# Generated by Django 6.0.5 on 2026-06-26 13:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_alter_parent_email_alter_parent_name_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS sis_staffprofile_subjects_taught;"),
                migrations.RunSQL("DROP TABLE IF EXISTS sis_staffprofile;"),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='staffprofile',
                ),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Rev.', 'Rev.')], default='Mr.', max_length=20)),
                ('full_name', models.CharField(default='', max_length=255)),
                ('staff_id', models.CharField(default='', max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date of Birth')),
                ('designation', models.CharField(default='', max_length=100)),
                ('ssnit_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='SSNIT ID')),
                ('email', models.EmailField(default='temp@example.com', max_length=254, unique=True)),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract')], default='Permanent', max_length=50)),
                ('date_of_appointment', models.DateField(default=datetime.date.today)),
                ('year_of_last_promotion', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=150)),
                ('certificate', models.CharField(default='', max_length=150)),
                ('name_of_institution_completed', models.CharField(default='', max_length=255)),
                ('year_completed', models.IntegerField(default=2000)),
                ('form_class', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_teacher', to='sis.classroom')),
                ('subject_areas', models.ManyToManyField(help_text='Select all subjects this staff member is assigned to teach.', related_name='teachers', to='sis.subject')),
            ],
        ),
    ]
