# Generated by Django 6.0.6 on 2026-06-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_remove_student_current_class_staffprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g., 2025/2026', max_length=20, unique=True)),
                ('is_current', models.BooleanField(default=False, help_text='True if this is the active academic year')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_grand_total', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum aggregate/grand total score required to qualify for promotion', max_digits=5)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_criteria', to='sis.classroom')),
            ],
            options={
                'verbose_name_plural': 'Promotion Criteria',
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_offered', to='sis.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_classes', to='sis.subject')),
            ],
            options={
                'verbose_name_plural': 'Class Subjects',
                'unique_together': {('classroom', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='True if this is the active grading term')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='sis.academicsession')),
            ],
            options={
                'unique_together': {('session', 'term_name')},
            },
        ),
    ]
