# Generated by Django 6.0.5 on 2026-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0008_academicsession_promotioncriteria_classsubject_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='classroom',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Used to sort classes hierarchically (e.g., Class 1 = 1, JHS 3 = 9)'),
        ),
    ]
