# Generated by Django 6.0.5 on 2026-06-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0009_alter_classroom_options_classroom_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff/profiles/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/profiles/'),
        ),
    ]
