# Generated by Django 6.0.5 on 2026-06-30 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0011_department_designation_alter_staffprofile_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.IntegerField()),
                ('academic_year', models.CharField(max_length=9)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_verifications', to='sis.classroom')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='sis.staffprofile')),
            ],
            options={
                'verbose_name': 'Grade Verification',
                'verbose_name_plural': 'Grade Verifications',
                'unique_together': {('classroom', 'term', 'academic_year')},
            },
        ),
    ]
