# Generated by Django 6.0.5 on 2026-06-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0012_gradeverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectassignment',
            options={'verbose_name': 'Student Subject Record', 'verbose_name_plural': 'Student Subject Records'},
        ),
        migrations.CreateModel(
            name='StaffClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='sis.classroom')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classes_subjects', to='sis.staffprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='sis.subject')),
            ],
            options={
                'verbose_name': 'Teacher Subject Assignment',
                'verbose_name_plural': 'Teacher Subject Assignments',
                'unique_together': {('staff', 'classroom', 'subject')},
            },
        ),
    ]
