# Generated by Django 6.0.5 on 2026-06-30 16:43

from django.db import migrations


def backfill_classroom(apps, schema_editor):
    Student = apps.get_model('sis', 'Student')
    Enrollment = apps.get_model('sis', 'Enrollment')

    for student in Student.objects.filter(classroom__isnull=True):
        latest_enrollment = (
            Enrollment.objects.filter(student=student)
            .order_by('-date_enrolled')
            .first()
        )
        if latest_enrollment:
            student.classroom = latest_enrollment.classroom
            student.save(update_fields=['classroom'])


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0014_student_classroom'),
    ]

    operations = [
        migrations.RunPython(backfill_classroom),
    ]
