# Generated by Django 6.0.5 on 2026-07-02 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0015_backfill_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='form_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_class', to='sis.staffprofile'),
        ),
    ]
