# Generated by Django 6.0.5 on 2026-07-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0016_classroom_form_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidTermRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('date_recorded', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.academicsession')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.classroom')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_records', to='sis.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.term')),
            ],
            options={
                'verbose_name': 'Mid-Term Record',
                'verbose_name_plural': 'Mid-Term Records',
                'unique_together': {('student', 'academic_session', 'term', 'subject')},
            },
        ),
    ]
