# Generated by Django 6.0.5 on 2026-07-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0017_midtermrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midtermrecord',
            old_name='score',
            new_name='midterm_score',
        ),
    ]
