# Generated by Django 6.0.5 on 2026-07-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0018_rename_score_midtermrecord_midterm_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
