# Generated by Django 6.0.5 on 2026-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0019_remove_staffprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='other_names',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='other_names',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
