# Generated by Django 6.0.5 on 2026-07-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0020_staffprofile_other_names_student_other_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
