# Generated by Django 6.0.5 on 2026-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0021_staffprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='residential_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
