# Generated by Django 6.0.5 on 2026-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0022_staffprofile_residential_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='residential_address',
            field=models.TextField(blank=True, null=True, verbose_name='Residential Address'),
        ),
    ]
