# Generated by Django 6.0.5 on 2026-07-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0023_alter_staffprofile_residential_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='residential_address',
            new_name='address',
        ),
    ]
