# Generated by Django 6.0.5 on 2026-07-11 23:49

import sis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0024_rename_residential_address_staffprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=sis.models.get_staff_photo_path),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='subject_areas',
            field=models.ManyToManyField(blank=True, help_text='Select all subjects this staff member is assigned to teach.', related_name='teachers', to='sis.subject'),
        ),
    ]
