# Generated by Django 6.0.5 on 2026-07-12 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0025_alter_staffprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradeverification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gradeverification',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sis.academicsession'),
        ),
        migrations.AddField(
            model_name='gradeverification',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sis.term'),
        ),
        migrations.AddField(
            model_name='subjectassessment',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sis.academicsession'),
        ),
        migrations.AddField(
            model_name='subjectassessment',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sis.term'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeverification',
            unique_together={('classroom', 'academic_session', 'academic_term')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectassessment',
            unique_together={('student', 'subject', 'academic_session', 'academic_term')},
        ),
    ]
