# Generated by Django 6.0.5 on 2026-07-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0026_alter_gradeverification_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='sis.term')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='sis.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='sis.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='sis.staffprofile')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('academic_term', 'class_assigned', 'day_of_week', 'start_time')},
            },
        ),
    ]
