# Generated by Django 6.0.5 on 2026-07-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0027_timetableslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='next_class',
            field=models.ForeignKey(blank=True, help_text='Explicitly define the next class students promote into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_class', to='sis.classroom'),
        ),
    ]
