# Generated by Django 6.0.5 on 2026-07-22 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0028_add_next_class_to_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_alumni',
            field=models.BooleanField(default=False, help_text='Set to True when student graduates (no next class)'),
        ),
        migrations.AddField(
            model_name='student',
            name='pending_next_class',
            field=models.ForeignKey(blank=True, help_text='Target class set during Term 3 promotion approval. Applied at session rollover.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_students', to='sis.classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='promotion_status',
            field=models.CharField(choices=[('NEUTRAL', 'Neutral'), ('APPROVED', 'Approved for Promotion'), ('HELD_BACK', 'Held Back')], default='NEUTRAL', help_text='NEUTRAL = no pending action, APPROVED = promoted at rollover, HELD_BACK = stays in current class', max_length=20),
        ),
    ]
