# Generated by Django 6.0.5 on 2026-07-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0030_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10),
        ),
    ]
