# Generated by Django 6.0.5 on 2026-07-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0032_timetable_timetableslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sis.academicsession'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sis.term'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'classroom', 'academic_session', 'academic_term')},
        ),
        migrations.DeleteModel(
            name='SubjectAssignment',
        ),
    ]
