# Generated by Django 6.0.6 on 2026-08-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0035_enforce_not_null_remove_legacy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['is_current'], name='sess_is_current_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['is_active'], name='term_is_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='only_one_current_session'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_term'),
        ),
    ]
